set background=dark

let mapleader=","

set relativenumber
set number

set shiftwidth=4
set tabstop=4

set ruler

set mouse=a

" Disable folds
set foldlevelstart=99

call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-obsession'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-commentary'

Plug 'Valloric/YouCompleteMe', { 'do': './install.py --go-completer' }

Plug 'sheerun/vim-polyglot'

Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

Plug 'rodjek/vim-puppet'

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

Plug 'nathangrigg/vim-beancount'

call plug#end()

let g:go_metalinter_autosave = 1
let g:go_fmt_command = "goimports"
